/**
 * Copyright Sp42 frank@ajaxjs.com Licensed under the Apache License, Version
 * 2.0 (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law
 * or agreed to in writing, software distributed under the License is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package com.ajaxjs.util.httpremote;

import com.ajaxjs.util.CommonConstant;
import com.ajaxjs.util.MapTool;
import com.ajaxjs.util.ObjectHelper;
import com.ajaxjs.util.StrUtil;
import com.ajaxjs.util.httpremote.model.HttpConstant;
import com.ajaxjs.util.io.DataWriter;
import lombok.Setter;

import java.io.*;
import java.net.URLConnection;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.regex.Pattern;

/**
 * Utility for writing a complete {@code multipart/form-data} request body
 * to an {@link OutputStream}.
 *
 * <p>This class only encodes multipart text and file parts; it does not create
 * or send HTTP requests. Use {@link MultipartPost} to send an upload via {@link Post}.</p>
 *
 * <p>Each call to one of the {@code write(...)} methods writes a complete
 * multipart body, including the final closing boundary. Therefore, a
 * {@code MultipartWriter} instance is intended to produce one complete
 * multipart request body.</p>
 *
 * <p>Do not call {@code write(...)} multiple times on the same output stream
 * in an attempt to append additional multipart fields after a previous
 * {@code write(...)} call has completed, because the previous call has
 * already written the terminating boundary.</p>
 *
 * <p>To send multiple fields or files in one multipart request, place all
 * parts into a single map and call {@link #write(Map)} once.</p>
 *
 * <p>The multipart boundary generated by this class must also be included in
 * the HTTP {@code Content-Type} header, for example:</p>
 *
 * <pre>{@code
 * Content-Type: multipart/form-data; boundary=<generated-boundary>
 * }</pre>
 *
 * <p>The supplied {@link OutputStream} is not closed by this class. Its
 * lifecycle remains the responsibility of the caller.</p>
 */
public class MultipartWriter implements CommonConstant {
    /**
     * Default multipart field name used by the convenience overloads that do
     * not explicitly receive a field name.
     *
     * <p>The default value is {@code "file"}.</p>
     */
    @Setter
    private String fieldName = "file";

    /**
     * Destination stream to which the complete multipart body is written.
     *
     * <p>This stream is not closed by this class.</p>
     */
    private final OutputStream out;

    /**
     * Boundary used to separate individual multipart parts.
     *
     * <p>The boundary contains only characters that can safely be used without
     * quoting it in the HTTP {@code Content-Type} header.</p>
     */
    private final String boundary;

    /**
     * Internal separator used to encode a multipart field name and a file name
     * into a single map key for raw {@link InputStream} and {@code byte[]}
     * file parts.
     *
     * <p>This value is an implementation detail and is not written to the
     * multipart request body.</p>
     */
    private static final String FILE_META_SEPARATOR = "\u0000";

    /**
     * Regular-expression-safe representation of {@link #FILE_META_SEPARATOR}.
     */
    private static final String FILE_META_SEPARATOR_REGEX = Pattern.quote(FILE_META_SEPARATOR);

    /**
     * Prefix required before every multipart boundary.
     */
    private static final String BOUNDARY_PREFIX = "--";

    /**
     * Template used to serialize a text multipart part.
     *
     * <p>The two consecutive CRLF sequences after the headers terminate the
     * header section and begin the part body.</p>
     */
    private static final String TEXT_PART = BOUNDARY_PREFIX + "${boundary}" + NEWLINE2
            + "Content-Disposition: form-data; name=\"${name}\"" + NEWLINE2
            + "Content-Type: text/plain; charset=UTF-8" + NEWLINE2 + NEWLINE2
            + "${value}";

    /**
     * Template used to serialize the headers of a file multipart part.
     *
     * <p>The template intentionally ends with two consecutive CRLF sequences:
     * the first terminates the final {@code Content-Type} header and the
     * second creates the mandatory empty line between multipart headers and
     * the binary file body.</p>
     *
     * <p>The actual file bytes are written immediately after this template.</p>
     */
    private static final String FILE_PART = BOUNDARY_PREFIX + "${boundary}" + NEWLINE2
            + "Content-Disposition: form-data; name=\"${name}\"; filename=\"${fileName}\"" + NEWLINE2
            + "Content-Type: ${contentType}" + NEWLINE2 + NEWLINE2;

    /**
     * Creates a multipart writer using an automatically generated boundary.
     *
     * <p>The generated boundary is based on a random UUID and is suitable for
     * direct use in an unquoted multipart {@code Content-Type} header.</p>
     *
     * @param out destination output stream
     * @throws NullPointerException if {@code out} is {@code null}
     */
    public MultipartWriter(OutputStream out) {
        this(out, "file-upload-" + UUID.randomUUID());
    }

    /**
     * Creates a multipart writer using the specified boundary.
     *
     * <p>The boundary must contain between 1 and 70 characters and may contain
     * only ASCII letters, digits, underscore and hyphen. This restricted
     * character set allows the boundary to be used directly in the HTTP
     * {@code Content-Type} header without quoting.</p>
     *
     * @param out      destination output stream
     * @param boundary multipart boundary
     * @throws NullPointerException     if {@code out} or {@code boundary} is  {@code null}
     * @throws IllegalArgumentException if the boundary does not satisfy the supported syntax
     */
    public MultipartWriter(OutputStream out, String boundary) {
        this.out = Objects.requireNonNull(out, "Output stream must not be null.");
        Objects.requireNonNull(boundary, "Boundary must not be null.");

        if (!boundary.matches("[A-Za-z0-9_-]{1,70}"))     // 使用无需在 Content-Type 中加引号的安全字符集。
            throw new IllegalArgumentException("Invalid multipart boundary.");

        this.boundary = boundary;
    }

    /**
     * Writes a complete multipart request containing one file using the
     * configured default field name.
     *
     * <p>The file name exposed in the multipart {@code Content-Disposition} header is taken from {@link File#getName()}.</p>
     *
     * <p>This method writes the terminating multipart boundary before returning.</p>
     *
     * @param file file to upload
     * @throws NullPointerException if {@code file} is {@code null}
     * @throws UncheckedIOException if an I/O error occurs while reading the  file or writing the request body
     */
    public void write(File file) {
        write(file, fieldName);
    }

    /**
     * Writes a complete multipart/form-data body containing a single file.
     *
     * <p>The supplied {@code fieldName} is used as the multipart form field name.
     * This method writes the final closing boundary before returning.</p>
     *
     * @param file      file to upload
     * @param fieldName multipart form field name
     * @throws IllegalArgumentException if an argument is invalid
     * @throws UncheckedIOException     if an I/O error occurs while writing
     */
    public void write(File file, String fieldName) {
        Objects.requireNonNull(file, "write.file");
        Objects.requireNonNull(fieldName, "write.fieldName");

        Map<String, Object> data = ObjectHelper.mapOf(fieldName, file);
        write(data);
    }

    /**
     * Writes a complete multipart/form-data body using the supplied input stream as file content.
     *
     * <p>The caller-provided {@link InputStream} is not closed by this method.
     * The caller remains responsible for closing it.</p>
     *
     * <p>This method writes the final closing boundary before returning.</p>
     *
     * @param in        input stream containing the file data
     * @param fileName  file name reported in the multipart Content-Disposition header
     * @param fieldName multipart form field name
     * @throws IllegalArgumentException if an argument is invalid
     * @throws UncheckedIOException     if an I/O error occurs while writing
     */
    public void write(InputStream in, String fileName, String fieldName) {
        Objects.requireNonNull(in, "write.in");
        Objects.requireNonNull(fileName, "write.fileName");
        Objects.requireNonNull(fieldName, "write.fieldName");

        Map<String, Object> data = ObjectHelper.mapOf(fieldName + FILE_META_SEPARATOR + fileName, in);
        write(data);
    }

    /**
     * Writes a complete multipart/form-data body using the supplied input stream
     * as file content and the default multipart field name.
     *
     * <p>The configured {@link #fieldName} is used as the multipart form field name.</p>
     *
     * <p>The caller-provided {@link InputStream} is not closed by this method.
     * The caller remains responsible for closing it.</p>
     *
     * <p>This method writes the final closing boundary before returning.</p>
     *
     * @param in       input stream containing the file data
     * @param fileName file name reported in the multipart {@code Content-Disposition} header
     * @throws NullPointerException if {@code in} or {@code fileName} is {@code null}
     * @throws UncheckedIOException if an I/O error occurs while writing
     */
    public void write(InputStream in, String fileName) {
        write(in, fileName, fieldName);
    }

    /**
     * Writes a complete multipart/form-data body using the supplied byte array
     * as file content.
     *
     * <p>The supplied {@code fileName} is written to the multipart
     * {@code Content-Disposition} header, while {@code fieldName} is used as the
     * multipart form field name.</p>
     *
     * <p>This method writes the final closing boundary before returning.</p>
     *
     * @param _data     file content
     * @param fileName  file name reported in the multipart {@code Content-Disposition} header
     * @param fieldName multipart form field name
     * @throws NullPointerException if any argument is {@code null}
     * @throws UncheckedIOException if an I/O error occurs while writing
     */
    public void write(byte[] _data, String fileName, String fieldName) {
        Objects.requireNonNull(_data, "write._data");
        Objects.requireNonNull(fileName, "write.fileName");
        Objects.requireNonNull(fieldName, "write.fieldName");

        Map<String, Object> data = ObjectHelper.mapOf(fieldName + FILE_META_SEPARATOR + fileName, _data);
        write(data);
    }

    /**
     * Writes a complete multipart/form-data body using the supplied byte array
     * as file content and the default multipart field name.
     *
     * <p>The configured {@link #fieldName} is used as the multipart form field name.</p>
     *
     * @param data     file content
     * @param fileName file name reported in the multipart {@code Content-Disposition} header
     * @throws NullPointerException if {@code data} or {@code fileName} is {@code null}
     * @throws UncheckedIOException if an I/O error occurs while writing
     */
    public void write(byte[] data, String fileName) {
        write(data, fileName, fieldName);
    }

    /**
     * Writes a complete multipart/form-data body containing all entries from
     * the supplied map.
     *
     * <p>Each map entry becomes one multipart part. File values may be supplied directly.
     * For raw InputStream and byte[] file content, use the dedicated overloads so that a file name can be provided.</p>
     *
     * <p>After all parts have been written, this method always writes the final
     * closing boundary:</p>
     *
     * <pre>{@code
     * --<boundary>--
     * }</pre>
     *
     * <p>Because the multipart body is finalized before this method returns,
     * callers must include every part required for the request in this single
     * invocation.</p>
     *
     * <p>The supplied {@link OutputStream} is flushed or closed only according to
     * the caller's surrounding request lifecycle; this method itself does not
     * close the output stream.</p>
     * <p>
     * For raw InputStream and byte[] values, use the dedicated overloads, because a filename is required to construct the multipart file part.
     *
     * @param data multipart field data; must not be null or empty
     * @throws IllegalArgumentException if {@code data} is null or empty
     * @throws UncheckedIOException     if an I/O error occurs while writing
     */
    public void write(Map<String, Object> data) {
        if (ObjectHelper.isEmpty(data))
            throw new IllegalArgumentException("Multipart data must not be null or empty.");

        try {
            for (String name : data.keySet()) {
                Object value = data.get(name);

                if (value instanceof byte[]) {
                    String[] arr = parseFileMeta(name);
                    name = arr[0];
                    String fileName = arr[1];
                    Map<String, String> params = ObjectHelper.mapOf("boundary", boundary, "name", name, "fileName", fileName);
                    writeFile(params);

                    byte[] _data = (byte[]) value;
                    out.write(_data);
                } else if (value instanceof InputStream) {
                    String[] arr = parseFileMeta(name);
                    name = arr[0];
                    String fileName = arr[1];
                    Map<String, String> params = ObjectHelper.mapOf("boundary", boundary, "name", name, "fileName", fileName);
                    writeFile(params);

                    InputStream in = (InputStream) value;

                    DataWriter.write(out, in);
                } else if (value instanceof File) {
                    File file = (File) value;
                    Map<String, String> params = ObjectHelper.mapOf("boundary", boundary, "name", name, "fileName", file.getName());
                    writeFile(params);

                    try (InputStream in = Files.newInputStream(file.toPath())) {
                        DataWriter.write(out, in);
                    }
                } else {
                    String str = value == null ? "" : value.toString();
                    Map<String, String> params = ObjectHelper.mapOf("boundary", boundary, "name", name, "value", str);
                    writeText(params);
                }

                out.write(NEWLINE2.getBytes(StandardCharsets.UTF_8));
            }

//        writeClosingBoundary(out, boundary);
            out.write((BOUNDARY_PREFIX + boundary + BOUNDARY_PREFIX + NEWLINE2).getBytes(StandardCharsets.UTF_8));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /**
     * Writes the header and body of a text multipart part.
     *
     * <p>The {@code params} map is expected to contain at least:</p>
     *
     * <ul>
     *     <li>{@code boundary} - multipart boundary</li>
     *     <li>{@code name} - multipart field name</li>
     *     <li>{@code value} - text field value</li>
     * </ul>
     *
     * <p>The field name is sanitized before being inserted into the multipart
     * header. The text value itself is not sanitized as a header value and may
     * contain normal text content, including line breaks.</p>
     *
     * @param params template parameters used to render the text part
     * @throws IOException if the multipart data cannot be written
     */
    void writeText(Map<String, String> params) throws IOException {
        params.put("name", sanitizeHeaderValue(params.get("name")));
        Map<String, Object> _params = MapTool.as(params, v -> v);

        byte[] fieldData = StrUtil.simpleTpl(TEXT_PART, _params).getBytes(StandardCharsets.UTF_8);
        out.write(fieldData);
    }

    /**
     * Writes the header of a file multipart part.
     *
     * <p>The {@code params} map is expected to contain at least:</p>
     *
     * <ul>
     *     <li>{@code boundary} - multipart boundary</li>
     *     <li>{@code name} - multipart field name</li>
     *     <li>{@code fileName} - file name exposed in the
     *     {@code Content-Disposition} header</li>
     * </ul>
     *
     * <p>The file content type is inferred from the file name. If no known MIME
     * type can be determined, {@link HttpConstant#FILE_TYPE} is used as the
     * fallback.</p>
     *
     * <p>This method writes only the multipart file header. The caller is
     * responsible for writing the actual file bytes immediately afterward.</p>
     *
     * @param params template parameters used to render the file part header
     * @throws IOException if the multipart header cannot be written
     */
    void writeFile(Map<String, String> params) throws IOException {
        String fileName = params.get("fileName");
        String contentType = getFileContentType(fileName);

        params.put("contentType", contentType);
        params.put("name", sanitizeHeaderValue(params.get("name")));
        params.put("fileName", sanitizeHeaderValue(fileName));

        Map<String, Object> _params = MapTool.as(params, v -> v);

        byte[] fieldData = StrUtil.simpleTpl(FILE_PART, _params).getBytes(StandardCharsets.UTF_8);
        out.write(fieldData);
    }

    /**
     * Validates and escapes a value that will be inserted into a multipart
     * header.
     *
     * <p>Carriage-return and line-feed characters are rejected to prevent
     * multipart/header injection. Backslashes and quotation marks are escaped so
     * that the value can safely be used inside a quoted header parameter.</p>
     *
     * @param value header value to validate and escape
     * @return escaped header value
     * @throws NullPointerException     if {@code value} is {@code null}
     * @throws IllegalArgumentException if {@code value} contains CR or LF
     */
    private static String sanitizeHeaderValue(String value) {
        Objects.requireNonNull(value, "Multipart header value");

        if (value.indexOf('\r') >= 0 || value.indexOf('\n') >= 0)
            throw new IllegalArgumentException("Multipart header value contains CR/LF.");

        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    /**
     * Parses the internally encoded multipart file metadata key.
     *
     * <p>For raw {@link InputStream} and {@code byte[]} file parts, the multipart
     * field name and file name are encoded into one internal map key separated by
     * {@link #FILE_META_SEPARATOR}. This method splits that representation back
     * into its two components.</p>
     *
     * @param name encoded multipart file metadata key
     * @return a two-element array where index {@code 0} is the multipart field
     * name and index {@code 1} is the file name
     * @throws NullPointerException     if {@code name} is {@code null}
     * @throws IllegalArgumentException if the expected file-name metadata is
     *                                  missing
     */
    private static String[] parseFileMeta(String name) {
        Objects.requireNonNull(name, "Multipart file field metadata");

        String[] arr = name.split(FILE_META_SEPARATOR_REGEX, 2);

        if (arr.length != 2 || arr[0].isEmpty() || arr[1].isEmpty())
            throw new IllegalArgumentException("Invalid multipart file metadata: " + name);

        return arr;
    }

    /**
     * Infers a MIME content type from a file name.
     *
     * <p>The lookup is performed using
     * {@link URLConnection#guessContentTypeFromName(String)}. If no content type
     * can be determined, {@link HttpConstant#FILE_TYPE} is returned.</p>
     *
     * @param fileName file name used for MIME type inference
     * @return inferred MIME type, or the generic binary file type as fallback
     * @throws NullPointerException if {@code fileName} is {@code null}
     */
    private static String getFileContentType(String fileName) {
        String type = URLConnection.guessContentTypeFromName(fileName);

        return type == null ? HttpConstant.FILE_TYPE : type;
    }

    /**
     * Returns the complete HTTP {@code Content-Type} value required for this
     * multipart request body.
     *
     * <p>The returned value includes both the multipart media type and the
     * boundary generated for this instance, for example:</p>
     *
     * <pre>{@code
     * multipart/form-data; boundary=file-upload-xxxxxxxx
     * }</pre>
     *
     * <p>This value should be used as the request's {@code Content-Type} header
     * before the body is written.</p>
     *
     * @return complete multipart/form-data content type including the boundary
     */
    public String getContentType() {
        return HttpConstant.CONTENT_TYPE_FORM_UPLOAD + "; boundary=" + boundary;
    }
}
