<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.ajaxjs</groupId>
        <artifactId>ajaxjs-parent</artifactId>
        <version>1.36</version>
        <relativePath/>
    </parent>

    <artifactId>aj-s3client</artifactId>
    <name>aj-s3client</name>
    <version>1.6</version>
    <packaging>jar</packaging>
    <description>A simple S3 client</description>

    <url>https://github.com/lightweight-component/aj-util/tree/main/aj-s3client</url>
    <scm>
        <url>https://github.com/lightweight-component/aj-util/tree/main/aj-s3client</url>
        <connection>scm:git:https://github.com/lightweight-component/aj-util.git</connection>
    </scm>
    <issueManagement>
        <system>Github Issues</system>
        <url>https://github.com/lightweight-component/aj-util/issues</url>
    </issueManagement>

    <dependencies>
        <dependency>
            <groupId>com.ajaxjs</groupId>
            <artifactId>aj-net</artifactId>
            <version>2.1</version>
        </dependency>

        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>1.33</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
