package com.ajaxjs.util.cryptography.rsa;

import com.ajaxjs.util.Base64Utils;
import com.ajaxjs.util.ObjectHelper;
import com.ajaxjs.util.cryptography.Constant;
import lombok.AllArgsConstructor;

import java.nio.charset.StandardCharsets;
import java.security.*;
import java.util.Objects;

/**
 * Provides RSA digital-signature generation utilities.
 *
 * <p>An instance is configured with a {@link PrivateKey} and a signature
 * algorithm. The default signature algorithm is {@code SHA256withRSA},
 * which combines SHA-256 message hashing with an RSA private-key signature.</p>
 *
 * <p>The signing operation follows the standard JCA
 * {@link Signature} workflow:</p>
 *
 * <ol>
 *     <li>Create a {@link Signature} instance for the configured algorithm.</li>
 *     <li>Initialize it with the configured RSA private key.</li>
 *     <li>Supply the input data to the signature engine.</li>
 *     <li>Generate the resulting signature bytes.</li>
 * </ol>
 *
 * <p>This class performs a real digital signature operation. It does not
 * emulate signing by using an RSA cipher in private-key encryption mode.</p>
 *
 * <p>String input is always converted to bytes using UTF-8, ensuring that
 * identical text produces identical input bytes across different operating
 * systems and JVM default charset configurations.</p>
 *
 * <p>The raw signature returned by {@link #sign(byte[])} is binary data.
 * When a textual representation is required, use
 * {@link #signToBase64(byte[])} or {@link #signToBase64(String)}.</p>
 *
 * <p>Instances contain only immutable signing configuration and do not retain
 * input data or generated signature results between calls. A new
 * {@link Signature} engine is created for every signing operation.</p>
 */
@AllArgsConstructor
public class DoSignature {
    /**
     * Signature algorithm used by this instance.
     *
     * <p>Typical RSA signature algorithms include {@code SHA256withRSA} and
     * {@code SHA512withRSA}. The exact set of supported algorithms depends on
     * the installed JCA security providers.</p>
     */
    private String algorithmName = Constant.SHA256_RSA;

    /**
     * RSA private key used to generate digital signatures.
     *
     * <p>The corresponding public key is required by the recipient to verify
     * signatures generated by this instance.</p>
     */
    private final PrivateKey privateKey;

    /**
     * Creates a signer using the default {@code SHA256withRSA} algorithm.
     *
     * @param privateKey the RSA private key used to generate signatures
     * @throws IllegalArgumentException if {@code privateKey} is {@code null}
     */
    public DoSignature(PrivateKey privateKey) {
        this.privateKey = privateKey;
    }

    /**
     * Creates an RSA signer from a Base64- or PEM-encoded private key string.
     *
     * <p>The signature algorithm defaults to {@code SHA256withRSA}.</p>
     *
     * <p>The supplied private key string is restored by
     * {@link RestoreKey#restorePrivateKey(String)} and must contain a supported
     * RSA private-key encoding. Typical supported input includes a Base64-encoded
     * PKCS#8 private key or a PEM value using the
     * {@code -----BEGIN PRIVATE KEY-----} / {@code -----END PRIVATE KEY-----}
     * boundaries.</p>
     *
     * <p>PKCS#1 private keys using
     * {@code -----BEGIN RSA PRIVATE KEY-----} are not supported unless
     * {@link RestoreKey#restorePrivateKey(String)} explicitly provides PKCS#1
     * conversion support.</p>
     *
     * @param privateKeyStr the Base64- or PEM-encoded RSA private key
     * @throws NullPointerException     if {@code privateKeyStr} is {@code null}
     * @throws IllegalArgumentException if the private-key encoding is invalid or cannot be restored as an RSA private key
     * @throws RuntimeException         if the RSA key factory algorithm is unavailable
     */
    public DoSignature(String privateKeyStr) {
        this(RestoreKey.restorePrivateKey(Objects.requireNonNull(privateKeyStr, "Signature2.privateKeyStr")));
    }

    /**
     * Generates a digital signature for UTF-8 text.
     *
     * <p>The supplied string is converted to bytes using
     * {@link StandardCharsets#UTF_8} and then passed to
     * {@link #sign(byte[])}.</p>
     *
     * @param data the text to sign
     * @return the raw binary signature bytes
     * @throws IllegalArgumentException if {@code data} is {@code null}, the configured algorithm is unavailable, or the private key is invalid
     * @throws IllegalStateException    if the underlying signature operation  fails
     */
    public byte[] sign(String data) {
        return sign(data.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Generates a digital signature for the supplied binary data.
     *
     * <p>A new {@link Signature} instance is created for every invocation.
     * The configured private key is used to initialize the signature engine,
     * after which all supplied bytes are signed.</p>
     *
     * <p>The returned bytes are the raw signature value and are not text.
     * Use {@link #signToBase64(byte[])} when the signature must be transmitted
     * through a text-based format such as JSON, XML, HTTP headers, or form
     * fields.</p>
     *
     * @param data the binary data to sign; an empty byte array is valid
     * @return the raw signature bytes
     * @throws IllegalArgumentException if {@code data} is {@code null}, the configured signature algorithm is not
     *                                  supported, or the private key cannot be used with that algorithm
     * @throws IllegalStateException    if the signature engine fails while processing or generating the signature
     */
    public byte[] sign(byte[] data) {
        if (ObjectHelper.isEmptyText(algorithmName))
            throw new IllegalStateException("Signature algorithm is required.");

        if (data == null)
            throw new IllegalStateException("Data to sign is required.");

        if (privateKey == null)
            throw new IllegalStateException("Private key is required.");

        try {
            Signature signature = Signature.getInstance(algorithmName);
            signature.initSign(privateKey);
            signature.update(data);

            return signature.sign();
        } catch (SignatureException e) {
            throw new IllegalStateException("Signature failed.", e);
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalArgumentException(Constant.NO_SUCH_ALGORITHM + algorithmName, e);
        } catch (InvalidKeyException e) {
            throw new IllegalArgumentException("Invalid Private Key", e);
        }
    }

    /**
     * Generates a digital signature for UTF-8 text and returns it as Base64.
     *
     * <p>This is a convenience method equivalent to signing the UTF-8 bytes
     * using {@link #sign(String)} and then Base64-encoding the resulting
     * signature bytes.</p>
     *
     * <p>Base64 is only a textual encoding of the signature; it does not add
     * encryption or additional cryptographic protection.</p>
     *
     * @param data the UTF-8 text to sign
     * @return the Base64-encoded digital signature
     * @throws IllegalArgumentException if the input, algorithm, or private key is invalid
     * @throws IllegalStateException    if the signature operation fails
     */
    public String signToBase64(String data) {
        return new Base64Utils(sign(data)).encodeAsString();
    }

    /**
     * Generates a digital signature for binary data and returns it as Base64.
     *
     * <p>This method is useful when the binary signature must be placed in a
     * textual transport or storage format.</p>
     *
     * @param data the binary data to sign
     * @return the Base64-encoded digital signature
     * @throws IllegalArgumentException if the input, algorithm, or private key is invalid
     * @throws IllegalStateException    if the signature operation fails
     */
    public String signToBase64(byte[] data) {
        return new Base64Utils(sign(data)).encodeAsString();
    }
}
