/**
 * Copyright Sp42 frank@ajaxjs.com Licensed under the Apache License, Version
 * 2.0 (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law
 * or agreed to in writing, software distributed under the License is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package com.ajaxjs.util.cryptography.aes;

import com.ajaxjs.util.ObjectHelper;
import com.ajaxjs.util.cryptography.CipherResult;
import com.ajaxjs.util.cryptography.DoCipher;
import com.ajaxjs.util.cryptography.SecretKeyMgr;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.SecretKeySpec;
import java.util.Arrays;

/**
 * Provides password-based authenticated encryption using a PBKDF2-derived AES
 * key and AES-GCM.
 *
 * <p>This class derives an AES key from a password, salt and iteration count,
 * and then uses the derived key with {@code AES/GCM/NoPadding} to encrypt and
 * decrypt UTF-8 text.</p>
 *
 * <p>The key derivation algorithm is determined by {@link SecretKeyMgr}. The derived key is converted
 * into an AES key and retained by this instance for subsequent cipher
 * operations.</p>
 *
 * <p>Each encryption operation generates a new random 12-byte (96-bit) GCM
 * nonce. The nonce is prepended to the encrypted result so that callers do not
 * need to store it separately.</p>
 *
 * <p>The binary format produced by {@link #encrypt(String)} is:</p>
 *
 * <pre>
 * +----------------+----------------------+------------------+
 * | GCM nonce      | ciphertext           | GCM tag          |
 * | 12 bytes       | variable length      | 16 bytes         |
 * +----------------+----------------------+------------------+
 * </pre>
 *
 * <p>The GCM authentication tag is generated by the JCA/JCE cipher operation
 * and is included at the end of the encrypted output. During decryption the
 * nonce is extracted from the first 12 bytes and the remaining ciphertext and
 * authentication tag are passed to AES-GCM for authenticated decryption.</p>
 *
 * <p>The salt is used only for password-based key derivation and is not included
 * in the value returned by {@link #encrypt(String)}. Applications must therefore
 * retain or transmit the salt separately when the derived key needs to be
 * reconstructed later.</p>
 *
 * <p><strong>Security requirements:</strong></p>
 * <ul>
 *     <li>The salt must contain at least {@value #PBE_SALT_LENGTH} bytes.</li>
 *     <li>The iteration count must be at least {@value #MIN_PBE_ITERATIONS}.</li>
 *     <li>A new random GCM nonce is generated for every encryption operation.</li>
 *     <li>The password should have sufficient entropy and must be protected appropriately.</li>
 * </ul>
 *
 * <p>Instances retain the derived AES key but do not retain nonce or cipher
 * state between operations.</p>
 *
 * @see PBEKeySpec
 * @see GCMParameterSpec
 * @see AesGcm
 * @see DoCipher
 */
public class AesPbe extends DoCipher {
    /**
     * Minimum salt length accepted by this implementation, in bytes.
     *
     * <p>The salt is used during password-based key derivation to ensure that
     * identical passwords do not normally produce identical derived keys.</p>
     */
    public static final int PBE_SALT_LENGTH = 16;

    /**
     * Length of the AES key derived from the password, in bits.
     *
     * <p>A value of 128 produces a 16-byte AES-128 key.</p>
     */
    private static final int PBE_KEY_LENGTH = 128;

    /**
     * Minimum password-based key-derivation iteration count accepted by this
     * implementation.
     *
     * <p>Higher iteration counts increase the computational cost of password
     * guessing but also increase legitimate key-derivation cost.</p>
     */
    public static final int MIN_PBE_ITERATIONS = 100_000;

    /**
     * Creates a password-based AES-GCM cipher.
     *
     * <p>The supplied password is combined with the salt and iteration count to
     * derive a {@value #PBE_KEY_LENGTH}-bit AES key. The derived key is retained
     * by this instance and used for subsequent encryption and decryption
     * operations.</p>
     *
     * <p>The same password, salt, iteration count and key-derivation algorithm
     * must be used when reconstructing an instance that needs to decrypt
     * previously encrypted data.</p>
     *
     * @param password       password used to derive the AES key
     * @param salt           salt used for password-based key derivation; must
     *                       contain at least {@value #PBE_SALT_LENGTH} bytes
     * @param iterationCount key-derivation iteration count; must be at least
     *                       {@value #MIN_PBE_ITERATIONS}
     * @throws IllegalArgumentException if the password is empty, the salt is too
     *                                  short, the iteration count is too small,
     *                                  or key derivation fails
     * @throws IllegalStateException    if the derived key cannot be encoded
     */
    public AesPbe(String password, byte[] salt, int iterationCount) {
        super(AesGcm.AES_GCM, derivePbeKey(password, salt, iterationCount));
    }

    /**
     * Encrypts UTF-8 text using the derived AES key and AES-GCM.
     *
     * <p>A new cryptographically secure 12-byte nonce is generated for every
     * invocation. The nonce is prepended to the AES-GCM encrypted output.</p>
     *
     * <p>The returned binary representation is:</p>
     *
     * <pre>
     * [12-byte nonce][ciphertext][16-byte authentication tag]
     * </pre>
     *
     * <p>The nonce does not need to be stored separately because it is included
     * in the returned byte array. The salt used to derive the AES key, however,
     * is not included and must be retained separately.</p>
     *
     * @param data plaintext to encrypt, interpreted as UTF-8 text
     * @return encrypted bytes containing the nonce, ciphertext and GCM authentication tag
     * @throws NullPointerException     if {@code data} is {@code null}
     * @throws IllegalArgumentException if encryption parameters are invalid
     * @throws IllegalStateException    if the cipher operation cannot be completed
     */
    public byte[] encrypt(String data) {
        byte[] nonce = randomBytes(AesGcm.GCM_NONCE_LENGTH);
        CipherResult encrypted = doCipher(Cipher.ENCRYPT_MODE, data, new GCMParameterSpec(AesGcm.GCM_TAG_LENGTH, nonce), null);

        return ObjectHelper.concat(nonce, encrypted.getResult());
    }

    /**
     * Decrypts data produced by {@link #encrypt(String)}.
     *
     * <p>The first AesGcm.GCM_NONCE_LENGTH bytes are interpreted as the
     * AES-GCM nonce. The remaining bytes contain the ciphertext followed by the
     * 128-bit authentication tag.</p>
     *
     * <p>AES-GCM verifies the authentication tag during decryption. Decryption
     * fails if the encrypted data, nonce, key or authentication tag does not
     * match the values used during encryption.</p>
     *
     * <p>The decrypted bytes are interpreted as UTF-8 text.</p>
     *
     * @param data encrypted bytes in the format {@code [nonce][ciphertext][authentication tag]}
     * @return decrypted plaintext interpreted as UTF-8
     * @throws IllegalArgumentException if {@code data} is missing or too short,
     *                                  authentication fails, or the ciphertext
     *                                  is otherwise invalid
     * @throws IllegalStateException    if the cipher operation cannot be completed
     */
    public String decrypt(byte[] data) {
        if (data == null || data.length < AesGcm.GCM_NONCE_LENGTH + AesGcm.GCM_TAG_LENGTH / Byte.SIZE)
            throw new IllegalArgumentException("PBE ciphertext is missing or too short.");

        return doCipher(Cipher.DECRYPT_MODE, Arrays.copyOfRange(data, AesGcm.GCM_NONCE_LENGTH, data.length),
                new GCMParameterSpec(AesGcm.GCM_TAG_LENGTH, Arrays.copyOf(data, AesGcm.GCM_NONCE_LENGTH)), null).toUtf8();
    }

    /**
     * Derives an AES key from a password using the configured password-based
     * key-derivation algorithm.
     *
     * <p>The password is supplied to a {@link PBEKeySpec} together with the
     * salt, iteration count and requested key length. The generated key bytes
     * are then wrapped in a {@link SecretKeySpec} for use with AES.</p>
     *
     * <p>The password held by {@link PBEKeySpec} is cleared in a
     * {@code finally} block after key derivation.</p>
     *
     * @param password       password used for key derivation
     * @param salt           key-derivation salt
     * @param iterationCount key-derivation iteration count
     * @return derived AES secret key
     * @throws IllegalArgumentException if the password is empty, the salt is too
     *                                  short, the iteration count is too small,
     *                                  or the key specification is invalid
     * @throws IllegalStateException    if the derived key cannot be encoded
     */
    static SecretKeySpec derivePbeKey(String password, byte[] salt, int iterationCount) {
        if (salt == null || salt.length < PBE_SALT_LENGTH)
            throw new IllegalArgumentException("PBE salt must contain at least " + PBE_SALT_LENGTH + " bytes.");

        if (iterationCount < MIN_PBE_ITERATIONS)
            throw new IllegalArgumentException("PBE iteration count must be at least " + MIN_PBE_ITERATIONS + ".");

        if (password == null || password.isEmpty())
            throw new IllegalArgumentException("PBE password must not be empty.");

        PBEKeySpec keySpec = new PBEKeySpec(password.toCharArray(), salt, iterationCount, PBE_KEY_LENGTH);

        try {
            SecretKey derivedKey = SecretKeyMgr.getSecretKey(keySpec);
            byte[] encoded = derivedKey.getEncoded();

            if (encoded == null)
                throw new IllegalStateException("Derived PBE key is not encodable.");

            return new SecretKeySpec(encoded, SecretKeyMgr.AES);
        } finally {
            keySpec.clearPassword();
        }
    }
}